export const INCREMENT_BY_ONE = 'INCREMENT_BY_ONE';
export const DECREMENT_BY_ONE = 'DECREMENT_BY_ONE';
export const ADD_USERDATA = 'ADD_USERDATA';
export const ADD_NAME = 'ADD_NAME';
export const ADD_ELEMENT_TO_ARRAY = 'ADD_ELEMENT_TO_ARRAY';
export const ADD_USER = 'ADD_USER';