// authReducer
export const CHECK_AUTH = 'CHECK_AUTH';
export const CHECK_AUTH_TRIGGER = 'CHECK_AUTH_TRIGGER';
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';
// quizReducer
export const QUIZ_SUBMIT = 'QUIZ_SUBMIT';
export const QUIZ_SUBMIT_SUCCESS = 'QUIZ_SUBMIT_SUCCESS';
export const QUIZ_SUBMIT_TRIGGER = 'QUIZ_SUBMIT_TRIGGER';
// dayReviewReducer
export const GET_DAY_REVIEW_ANSWERS = 'GET_DAY_REVIEW_ANSWERS';
export const GET_DAY_REVIEW_ANSWERS_SUCCESS = 'GET_DAY_REVIEW_ANSWERS_SUCCESS';
export const GET_DAY_REVIEW_ANSWERS_TRIGGER = 'GET_DAY_REVIEW_ANSWERS_TRIGGER';
// overviewReducer
export const GET_OVERVIEW_ANSWERS = 'GET_OVERVIEW_ANSWERS';
export const GET_OVERVIEW_ANSWERS_SUCCESS = 'GET_OVERVIEW_ANSWERS_SUCCESS';
export const GET_OVERVIEW_ANSWERS_TRIGGER = 'GET_OVERVIEW_ANSWERS_TRIGGER';
