export const CHECK_AUTH = 'CHECK_AUTH';
export const CHECK_AUTH_TRIGGER = 'CHECK_AUTH_TRIGGER';
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';

export const QUIZ_SUBMIT = 'QUIZ_SUBMIT';
export const QUIZ_SUBMIT_SUCCESS = 'QUIZ_SUBMIT_SUCCESS';
export const QUIZ_SUBMIT_TRIGGER = 'QUIZ_SUBMIT_TRIGGER';

export const GET_ANSWERS_BY_DAY = 'GET_ANSWERS_BY_DAY';
export const GET_ANSWERS_BY_DAY_SUCCESS = 'GET_ANSWERS_BY_DAY_SUCCESS';
export const GET_ANSWERS_BY_DAY_TRIGGER = 'GET_ANSWERS_BY_DAY_TRIGGER';