version: 2.1
orbs:
  node: circleci/node@1.1
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  test:
    executor:
      name: node/default
      tag: '12.19'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run test
      - persist_to_workspace:
          root: ./
          paths:
           - '*'

  build:
    executor:
      name: node/default
      tag: '12.19'
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
           - build

  deploy:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - aws-s3/copy:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_ACCESS_SECRET
          arguments: '--recursive'
          from: ./
          to: 's3://hwyd-app'

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
