version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '12.19'
    steps:
      - checkout
      - node/with-cache:
        steps:
          - run: npm install
      - run: npm run build
  test:
    executor:
      name: node/default
      tag: '12.19'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
           - test
