version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  install_and_run_tests:
    executor:
      name: node/default
      tag: '12.19'

    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test

   build:
    executor:
      name: node/default
      tag: '12.19'

    steps:
      - run: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_and_run_tests
      - build
