version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '12.19'
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run build
  test:
    executor:
      name: node/default
      tag: '12.19'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run test
      - persist_to_workspace:
          root: ./
          paths:
           - '*'

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
