export const CATEGORY_SLEEP = 'CATEGORY_SLEEP';
export const CATEGORY_NUTRITION = 'CATEGORY_NUTRITION';
export const CATEGORY_ACTIVITY = 'CATEGORY_ACTIVITY';

export const INPUT_NUMBER = 'INPUT_NUMBER';
export const INPUT_RADIOBUTTON = 'INPUT_RADIOBUTTON';
export const INPUT_COMBINED_SELECT_NUMBER = 'INPUT_COMBINED_SELECT_NUMBER';
export const INPUT_HOUR = 'HOUR'


